-- MySQL Script generated by MySQL Workbench
-- ma. 12. mars 2018 kl. 19.27 +0100
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SykkelUtleie
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SykkelUtleie
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SykkelUtleie` DEFAULT CHARACTER SET utf8 ;
USE `SykkelUtleie` ;

-- -----------------------------------------------------
-- Table `SykkelUtleie`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SykkelUtleie`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SykkelUtleie`.`Equipment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SykkelUtleie`.`Equipment` (
  `idEquipment` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idEquipment`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SykkelUtleie`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SykkelUtleie`.`Employee` (
  `idEmployee` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idEmployee`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SykkelUtleie`.`Department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SykkelUtleie`.`Department` (
  `idDepartment` INT NOT NULL AUTO_INCREMENT,
  `Equipment_idEquipment` INT NOT NULL,
  `Employee_idEmployee` INT NOT NULL,
  PRIMARY KEY (`idDepartment`, `Equipment_idEquipment`),
  INDEX `fk_Department_Equipment1_idx` (`Equipment_idEquipment` ASC),
  INDEX `fk_Department_Employee1_idx` (`Employee_idEmployee` ASC),
  CONSTRAINT `fk_Department_Equipment1`
    FOREIGN KEY (`Equipment_idEquipment`)
    REFERENCES `SykkelUtleie`.`Equipment` (`idEquipment`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Department_Employee1`
    FOREIGN KEY (`Employee_idEmployee`)
    REFERENCES `SykkelUtleie`.`Employee` (`idEmployee`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SykkelUtleie`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SykkelUtleie`.`Order` (
  `idOrder` INT NOT NULL AUTO_INCREMENT,
  `Department_idDepartment` INT NOT NULL,
  `OrderFrom` DATETIME NOT NULL,
  `OrderTo` DATETIME NOT NULL,
  PRIMARY KEY (`idOrder`),
  INDEX `fk_Order_Department1_idx` (`Department_idDepartment` ASC),
  CONSTRAINT `fk_Order_Department1`
    FOREIGN KEY (`Department_idDepartment`)
    REFERENCES `SykkelUtleie`.`Department` (`idDepartment`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Order_1`
    FOREIGN KEY (`idOrder`)
    REFERENCES `SykkelUtleie`.`User` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SykkelUtleie`.`Records`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SykkelUtleie`.`Records` (
  `Department_idDepartment` INT NOT NULL,
  `OrderId` INT NOT NULL,
  INDEX `fk_Records_Department1_idx` (`Department_idDepartment` ASC),
  INDEX `fk_Records_1_idx` (`OrderId` ASC),
  PRIMARY KEY (`OrderId`),
  CONSTRAINT `fk_Records_Department1`
    FOREIGN KEY (`Department_idDepartment`)
    REFERENCES `SykkelUtleie`.`Department` (`idDepartment`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Records_1`
    FOREIGN KEY (`OrderId`)
    REFERENCES `SykkelUtleie`.`Order` (`idOrder`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

---sdfhfhfjkhsdfjk


-- -----------------------------------------------------
-- Table `SykkelUtleie`.`Repair`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SykkelUtleie`.`Repair` (
  `idRepair` INT NOT NULL,
  PRIMARY KEY (`idRepair`),
  CONSTRAINT `fk_Repair_1`
    FOREIGN KEY (`idRepair`)
    REFERENCES `SykkelUtleie`.`Equipment` (`idEquipment`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Repair_2`
    FOREIGN KEY ()
    REFERENCES `SykkelUtleie`.`Employee` ()
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SykkelUtleie`.`Bike`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SykkelUtleie`.`Bike` (
  `idBike` INT NOT NULL,
  PRIMARY KEY (`idBike`),
  CONSTRAINT `fk_Bike_1`
    FOREIGN KEY (`idBike`)
    REFERENCES `SykkelUtleie`.`Equipment` (`idEquipment`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SykkelUtleie`.`Delivered`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SykkelUtleie`.`Delivered` (
  `idDelivered` INT NOT NULL,
  `Department_idDepartment` INT NOT NULL,
  `Department_Equipment_idEquipment` INT NOT NULL,
  PRIMARY KEY (`idDelivered`, `Department_idDepartment`, `Department_Equipment_idEquipment`),
  INDEX `fk_Delivered_Department1_idx` (`Department_idDepartment` ASC, `Department_Equipment_idEquipment` ASC),
  CONSTRAINT `fk_Delivered_1`
    FOREIGN KEY ()
    REFERENCES `SykkelUtleie`.`Equipment` ()
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Delivered_2`
    FOREIGN KEY (`idDelivered`)
    REFERENCES `SykkelUtleie`.`Employee` (`idEmployee`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Delivered_Department1`
    FOREIGN KEY (`Department_idDepartment` , `Department_Equipment_idEquipment`)
    REFERENCES `SykkelUtleie`.`Department` (`idDepartment` , `Equipment_idEquipment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
